steps:
  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    entrypoint: gcloud
    args:
      - functions
      - deploy
      - getAvailableBlocks
      - --gen2
      - --runtime=nodejs20
      - --region=us-central1        # change if needed
      - --entry-point=getAvailableBlocks
      - --source=.
      - --trigger-http
      - --allow-unauthenticated
      - --set-secrets=AIRTABLE_TOKEN=projects/PROJECT_ID/secrets/AIRTABLE_TOKEN:latest
      - --set-env-vars=AIRTABLE_BASE_ID=appXXXXXXXXXXXX,TIMEZONE=America/Los_Angeles
