substitutions:
  _REGION: us-west1
  _FUNC_NAME: fetchEventBlocks
  _ENTRY: fetchEventBlocks
  _RUNTIME: nodejs20
  _TIMEOUT: 30s
  _MEMORY: 256Mi
  # Non-secrets here:
  _ENVS: >
    --set-env-vars=AIRTABLE_BASE_ID=app1L7NbGnRnRZ8UD,
    TIMEZONE=America/Los_Angeles
  # Secrets here:
  _SECRETS: >
    --set-secrets=AIRTABLE_TOKEN=projects/$PROJECT_ID/secrets/AIRTABLE_TOKEN:latest

steps:
  - name: gcr.io/google.com/cloudsdktool/cloud-sdk:slim
    entrypoint: bash
    args:
      - -lc
      - |
        set -euo pipefail
        gcloud functions deploy ${_FUNC_NAME} \
          --gen2 \
          --region=${_REGION} \
          --runtime=${_RUNTIME} \
          --entry-point=${_ENTRY} \
          --trigger-http \
          --allow-unauthenticated \
          ${_ENVS} \
          ${_SECRETS} \
          --timeout=${_TIMEOUT} \
          --memory=${_MEMORY} \
          --quiet

logging: CLOUD_LOGGING_ONLY
